/*******************************************************/
/**  Autogenerated phoneset trees for cmu_th    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_th_phoneset;


static const char * const cmu_th_featnames[] = {
 "vc",
 "voicing",
 "place",
 "ctype",
 "rounding",
 "height",
 "frontness",
 "length",
 "level",
 NULL };

static const char * const cmu_th_phonenames[] = {
 "p",
 "ph",
 "pt",
 "b",
 "t",
 "th",
 "tt",
 "d",
 "c",
 "tl",
 "k",
 "kh",
 "kt",
 "m",
 "n",
 "n1",
 "n2",
 "f",
 "s",
 "h",
 "r",
 "l",
 "y",
 "w",
 "j",
 "tg",
 "ta",
 "tgh",
 "tah",
 "q",
 "a",
 "a1",
 "a2",
 "i",
 "i1",
 "u",
 "u1",
 "e",
 "e1",
 "ee",
 "ee1",
 "o",
 "o1",
 "ww",
 "w1",
 "rr",
 "r1",
 "c2",
 "c1",
 "1",
 "2",
 "3",
 "4",
 "ia",
 "iaq",
 "waq",
 "wa",
 "uaq",
 "ua",
 "pau",
 NULL };

static const int cmu_th_fv_000[] = { 0, 1, 2, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_001[] = { 0, 1, 2, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_002[] = { 0, 1, 2, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_003[] = { 0, 5, 2, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_004[] = { 0, 1, 6, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_005[] = { 0, 1, 6, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_006[] = { 0, 1, 6, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_007[] = { 0, 5, 6, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_008[] = { 0, 1, 7, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_009[] = { 0, 1, 8, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_010[] = { 0, 1, 9, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_011[] = { 0, 1, 9, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_012[] = { 0, 1, 9, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_013[] = { 0, 5, 2, 10, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_014[] = { 0, 5, 11, 10, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_015[] = { 0, 5, 7, 10, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_016[] = { 0, 5, 12, 10, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_017[] = { 0, 1, 2, 13, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_018[] = { 0, 1, 6, 13, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_019[] = { 0, 1, 9, 13, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_020[] = { 0, 5, 11, 14, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_021[] = { 0, 5, 11, 15, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_022[] = { 0, 5, 9, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_023[] = { 0, 5, 2, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_024[] = { 0, 5, 7, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_025[] = { 0, 1, 7, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_026[] = { 0, 1, 7, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_027[] = { 0, 1, 7, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_028[] = { 0, 1, 7, 16, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_029[] = { 0, 1, 12, 3, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_030[] = { 17, 4, 4, 4, 18, 19, 20, 21, 4,   -1 };
static const int cmu_th_fv_031[] = { 17, 4, 4, 4, 18, 19, 20, 21, 4,   -1 };
static const int cmu_th_fv_032[] = { 17, 4, 4, 4, 18, 19, 20, 22, 4,   -1 };
static const int cmu_th_fv_033[] = { 17, 4, 4, 4, 18, 19, 23, 21, 4,   -1 };
static const int cmu_th_fv_034[] = { 17, 4, 4, 4, 18, 19, 23, 22, 4,   -1 };
static const int cmu_th_fv_035[] = { 17, 4, 4, 4, 18, 24, 20, 21, 4,   -1 };
static const int cmu_th_fv_036[] = { 17, 4, 4, 4, 18, 24, 20, 22, 4,   -1 };
static const int cmu_th_fv_037[] = { 17, 4, 4, 4, 18, 25, 23, 21, 4,   -1 };
static const int cmu_th_fv_038[] = { 17, 4, 4, 4, 18, 25, 23, 22, 4,   -1 };
static const int cmu_th_fv_039[] = { 17, 4, 4, 4, 18, 26, 23, 21, 4,   -1 };
static const int cmu_th_fv_040[] = { 17, 4, 4, 4, 18, 25, 23, 22, 4,   -1 };
static const int cmu_th_fv_041[] = { 17, 4, 4, 4, 18, 25, 20, 21, 4,   -1 };
static const int cmu_th_fv_042[] = { 17, 4, 4, 4, 18, 25, 20, 22, 4,   -1 };
static const int cmu_th_fv_043[] = { 17, 4, 4, 4, 18, 24, 20, 21, 4,   -1 };
static const int cmu_th_fv_044[] = { 17, 4, 4, 4, 18, 24, 20, 22, 4,   -1 };
static const int cmu_th_fv_045[] = { 17, 4, 4, 4, 18, 27, 20, 21, 4,   -1 };
static const int cmu_th_fv_046[] = { 17, 4, 4, 4, 18, 27, 20, 22, 4,   -1 };
static const int cmu_th_fv_047[] = { 17, 4, 4, 4, 28, 26, 20, 21, 4,   -1 };
static const int cmu_th_fv_048[] = { 17, 4, 4, 4, 28, 26, 20, 22, 4,   -1 };
static const int cmu_th_fv_049[] = { 29, 4, 4, 4, 4, 4, 4, 4, 30,   -1 };
static const int cmu_th_fv_050[] = { 29, 4, 4, 4, 4, 4, 4, 4, 31,   -1 };
static const int cmu_th_fv_051[] = { 29, 4, 4, 4, 4, 4, 4, 4, 32,   -1 };
static const int cmu_th_fv_052[] = { 29, 4, 4, 4, 4, 4, 4, 4, 33,   -1 };
static const int cmu_th_fv_053[] = { 34, 4, 4, 4, 4, 4, 23, 35, 4,   -1 };
static const int cmu_th_fv_054[] = { 34, 4, 4, 4, 4, 4, 23, 35, 4,   -1 };
static const int cmu_th_fv_055[] = { 34, 4, 4, 4, 4, 4, 36, 35, 4,   -1 };
static const int cmu_th_fv_056[] = { 34, 4, 4, 4, 4, 4, 36, 35, 4,   -1 };
static const int cmu_th_fv_057[] = { 34, 4, 4, 4, 4, 4, 20, 35, 4,   -1 };
static const int cmu_th_fv_058[] = { 34, 4, 4, 4, 4, 4, 20, 35, 4,   -1 };
static const int cmu_th_fv_059[] = { 37, 4, 4, 4, 4, 4, 4, 4, 4,   -1 };
static const int cmu_th_fv_060[] = { 0 };

static const int * const cmu_th_fvtable[] = {
  cmu_th_fv_000, 
  cmu_th_fv_001, 
  cmu_th_fv_002, 
  cmu_th_fv_003, 
  cmu_th_fv_004, 
  cmu_th_fv_005, 
  cmu_th_fv_006, 
  cmu_th_fv_007, 
  cmu_th_fv_008, 
  cmu_th_fv_009, 
  cmu_th_fv_010, 
  cmu_th_fv_011, 
  cmu_th_fv_012, 
  cmu_th_fv_013, 
  cmu_th_fv_014, 
  cmu_th_fv_015, 
  cmu_th_fv_016, 
  cmu_th_fv_017, 
  cmu_th_fv_018, 
  cmu_th_fv_019, 
  cmu_th_fv_020, 
  cmu_th_fv_021, 
  cmu_th_fv_022, 
  cmu_th_fv_023, 
  cmu_th_fv_024, 
  cmu_th_fv_025, 
  cmu_th_fv_026, 
  cmu_th_fv_027, 
  cmu_th_fv_028, 
  cmu_th_fv_029, 
  cmu_th_fv_030, 
  cmu_th_fv_031, 
  cmu_th_fv_032, 
  cmu_th_fv_033, 
  cmu_th_fv_034, 
  cmu_th_fv_035, 
  cmu_th_fv_036, 
  cmu_th_fv_037, 
  cmu_th_fv_038, 
  cmu_th_fv_039, 
  cmu_th_fv_040, 
  cmu_th_fv_041, 
  cmu_th_fv_042, 
  cmu_th_fv_043, 
  cmu_th_fv_044, 
  cmu_th_fv_045, 
  cmu_th_fv_046, 
  cmu_th_fv_047, 
  cmu_th_fv_048, 
  cmu_th_fv_049, 
  cmu_th_fv_050, 
  cmu_th_fv_051, 
  cmu_th_fv_052, 
  cmu_th_fv_053, 
  cmu_th_fv_054, 
  cmu_th_fv_055, 
  cmu_th_fv_056, 
  cmu_th_fv_057, 
  cmu_th_fv_058, 
  cmu_th_fv_059, 
 cmu_th_fv_060 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"consonant");
DEF_STATIC_CONST_VAL_STRING(featval_1,"voiceless");
DEF_STATIC_CONST_VAL_STRING(featval_2,"bilabial");
DEF_STATIC_CONST_VAL_STRING(featval_3,"p");
DEF_STATIC_CONST_VAL_STRING(featval_4,"0");
DEF_STATIC_CONST_VAL_STRING(featval_5,"voiced");
DEF_STATIC_CONST_VAL_STRING(featval_6,"dental");
DEF_STATIC_CONST_VAL_STRING(featval_7,"palatal");
DEF_STATIC_CONST_VAL_STRING(featval_8,"retroflex");
DEF_STATIC_CONST_VAL_STRING(featval_9,"velar");
DEF_STATIC_CONST_VAL_STRING(featval_10,"n");
DEF_STATIC_CONST_VAL_STRING(featval_11,"alveolar");
DEF_STATIC_CONST_VAL_STRING(featval_12,"glottal");
DEF_STATIC_CONST_VAL_STRING(featval_13,"f");
DEF_STATIC_CONST_VAL_STRING(featval_14,"r");
DEF_STATIC_CONST_VAL_STRING(featval_15,"l");
DEF_STATIC_CONST_VAL_STRING(featval_16,"a");
DEF_STATIC_CONST_VAL_STRING(featval_17,"vowel");
DEF_STATIC_CONST_VAL_STRING(featval_18,"unrounded");
DEF_STATIC_CONST_VAL_STRING(featval_19,"open");
DEF_STATIC_CONST_VAL_STRING(featval_20,"back");
DEF_STATIC_CONST_VAL_STRING(featval_21,"default");
DEF_STATIC_CONST_VAL_STRING(featval_22,"long");
DEF_STATIC_CONST_VAL_STRING(featval_23,"front");
DEF_STATIC_CONST_VAL_STRING(featval_24,"close");
DEF_STATIC_CONST_VAL_STRING(featval_25,"mid");
DEF_STATIC_CONST_VAL_STRING(featval_26,"mid-low");
DEF_STATIC_CONST_VAL_STRING(featval_27,"mid-high");
DEF_STATIC_CONST_VAL_STRING(featval_28,"rounded");
DEF_STATIC_CONST_VAL_STRING(featval_29,"tone");
DEF_STATIC_CONST_VAL_STRING(featval_30,"low");
DEF_STATIC_CONST_VAL_STRING(featval_31,"falling");
DEF_STATIC_CONST_VAL_STRING(featval_32,"high");
DEF_STATIC_CONST_VAL_STRING(featval_33,"rising");
DEF_STATIC_CONST_VAL_STRING(featval_34,"diph");
DEF_STATIC_CONST_VAL_STRING(featval_35,"diphthong");
DEF_STATIC_CONST_VAL_STRING(featval_36,"central");
DEF_STATIC_CONST_VAL_STRING(featval_37,"silence");

static const cst_val * const cmu_th_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 (cst_val *)&featval_16,
 (cst_val *)&featval_17,
 (cst_val *)&featval_18,
 (cst_val *)&featval_19,
 (cst_val *)&featval_20,
 (cst_val *)&featval_21,
 (cst_val *)&featval_22,
 (cst_val *)&featval_23,
 (cst_val *)&featval_24,
 (cst_val *)&featval_25,
 (cst_val *)&featval_26,
 (cst_val *)&featval_27,
 (cst_val *)&featval_28,
 (cst_val *)&featval_29,
 (cst_val *)&featval_30,
 (cst_val *)&featval_31,
 (cst_val *)&featval_32,
 (cst_val *)&featval_33,
 (cst_val *)&featval_34,
 (cst_val *)&featval_35,
 (cst_val *)&featval_36,
 (cst_val *)&featval_37,
 NULL };

const cst_phoneset cmu_th_phoneset = {
  "cmu_th",
  cmu_th_featnames,
  cmu_th_featvals,
  cmu_th_phonenames,
  "pau",
  60,
  cmu_th_fvtable,
  0  /* not freeable */
};
